export const metadata = {
  title: 'Universre | Home',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/x-icon" href="images/favicon.ico" />
      </head>
      <body>{children}</body>
    </html>
  )
}
